### ISSUE TITLE
Should this be failing if there is an issue in a filtered finding?

### ISSUE THREAD

**Issue by tmc** [reviewdog/action-staticcheck#10]
I'm seeing this behavior:

![Screen Shot 2020-11-09 at 3 49 44 PM](https://user-images.githubusercontent.com/3977/98609894-3d656180-22a3-11eb-922f-2fce0749048a.png)

With this config:
```yaml
  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
```

Is it expected to fail a PR if there are no newly introduced lint issues?
