### ISSUE TITLE
Go 1.18

### ISSUE THREAD

**Issue by brurucy** [reviewdog/action-staticcheck#26]
`staticcheck` already supports go 1.18, but review dog doesn't

Is there a release on the way?

**Comment by shogo82148** [comment]
see https://github.com/reviewdog/action-golangci-lint/issues/73#issuecomment-813386935

We should add the following snippet into the examples in README.

```yaml
- use: actions/setup-go@v3
  with:
    go-version: "1.18"
```
